### ISSUE TITLE
Center images on the ReadME or make them adapt to width

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/flutter-portfolio#11]
Should be an easy fix adjusting the width.

**Comment by gantanikhilraj** [comment]
I have finished this and raised a PR please check

**Comment by adityathakurxd** [comment]
Have left thoughts on the PR. Also. it is appreciated practice if you can comment on the issue before taking it up. Generally a maintainer can assign you the issue and others will know it is being worked on.

**Comment by gantanikhilraj** [comment]
Thanks for the suggestion, I will work on it
